# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170221_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pw_hash',
        ),
    ]
