# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20170224_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name=['%Y-%m-%d %H:%M:%S']),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name=['%Y-%m-%d %H:%M:%S']),
        ),
    ]
