# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20170224_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name=['%d/%m/%Y']),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name=['%d/%m/%Y']),
        ),
    ]
